// fonts.js — catalog of selectable fonts (first 164 from curated list)
// Each entry: fontName (id), displayName (UI), cssStack (applied), provider (google|system|other),
// gf (Google Fonts family query portion) when provider === 'google'.
// NOTE: We intentionally include only common weight axes (400,600,700) for performance.
// You can extend with additional weights or variable axes if needed.

export const FONT_CATALOG = [
  { fontName:'original_default', displayName:'Original Default', cssStack:'system-ui, -apple-system, Segoe UI, Roboto, Ubuntu, Cantarell, "Helvetica Neue", Arial, "Noto Sans", sans-serif', provider:'system' },
  { fontName:'inter', displayName:'Inter', cssStack:'"Inter", system-ui, -apple-system, "Segoe UI", Roboto, Arial, sans-serif', provider:'google', gf:'Inter:wght@400;500;600;700' },
  { fontName:'roboto', displayName:'Roboto', cssStack:'"Roboto", system-ui, -apple-system, "Segoe UI", Helvetica, Arial, sans-serif', provider:'google', gf:'Roboto:wght@400;500;700' },
  { fontName:'open_sans', displayName:'Open Sans', cssStack:'"Open Sans", "Helvetica Neue", Arial, sans-serif', provider:'google', gf:'Open+Sans:wght@400;600;700' },
  { fontName:'source_sans_3', displayName:'Source Sans 3', cssStack:'"Source Sans 3", system-ui, -apple-system, "Segoe UI", Roboto, Arial, sans-serif', provider:'google', gf:'Source+Sans+3:wght@400;600;700' },
  { fontName:'noto_sans', displayName:'Noto Sans', cssStack:'"Noto Sans", system-ui, -apple-system, "Segoe UI", Roboto, Arial, sans-serif', provider:'google', gf:'Noto+Sans:wght@400;600;700' },
  { fontName:'lato', displayName:'Lato', cssStack:'"Lato", "Helvetica Neue", Arial, sans-serif', provider:'google', gf:'Lato:wght@400;700' },
  { fontName:'poppins', displayName:'Poppins', cssStack:'"Poppins", "Helvetica Neue", Arial, sans-serif', provider:'google', gf:'Poppins:wght@400;500;600;700' },
  { fontName:'montserrat', displayName:'Montserrat', cssStack:'"Montserrat", "Helvetica Neue", Arial, sans-serif', provider:'google', gf:'Montserrat:wght@400;500;600;700' },
  { fontName:'nunito', displayName:'Nunito', cssStack:'"Nunito", system-ui, -apple-system, "Segoe UI", Roboto, Arial, sans-serif', provider:'google', gf:'Nunito:wght@400;600;700' },
  { fontName:'work_sans', displayName:'Work Sans', cssStack:'"Work Sans", system-ui, -apple-system, "Segoe UI", Roboto, Arial, sans-serif', provider:'google', gf:'Work+Sans:wght@400;600;700' },
  { fontName:'manrope', displayName:'Manrope', cssStack:'"Manrope", system-ui,-apple-system,"Segoe UI",Roboto,Arial,sans-serif', provider:'google', gf:'Manrope:wght@400;600;700' },
  { fontName:'ibm_plex_sans', displayName:'IBM Plex Sans', cssStack:'"IBM Plex Sans", "Helvetica Neue", Arial, sans-serif', provider:'google', gf:'IBM+Plex+Sans:wght@400;500;600;700' },
  { fontName:'ubuntu', displayName:'Ubuntu', cssStack:'"Ubuntu", system-ui, -apple-system, "Segoe UI", Roboto, Arial, sans-serif', provider:'google', gf:'Ubuntu:wght@400;500;700' },
  { fontName:'figtree', displayName:'Figtree', cssStack:'"Figtree", system-ui, -apple-system, "Segoe UI", Roboto, Arial, sans-serif', provider:'google', gf:'Figtree:wght@400;600;700' },
  { fontName:'plus_jakarta_sans', displayName:'Plus Jakarta Sans', cssStack:'"Plus Jakarta Sans", system-ui, -apple-system, "Segoe UI", Roboto, Arial, sans-serif', provider:'google', gf:'Plus+Jakarta+Sans:wght@400;600;700' },
  { fontName:'dm_sans', displayName:'DM Sans', cssStack:'"DM Sans", system-ui, -apple-system, "Segoe UI", Roboto, Arial, sans-serif', provider:'google', gf:'DM+Sans:wght@400;500;700' },
  { fontName:'mulish', displayName:'Mulish', cssStack:'"Mulish", system-ui,-apple-system,"Segoe UI",Roboto,Arial,sans-serif', provider:'google', gf:'Mulish:wght@400;600;700' },
  { fontName:'outfit', displayName:'Outfit', cssStack:'"Outfit", system-ui,-apple-system,"Segoe UI",Roboto,Arial,sans-serif', provider:'google', gf:'Outfit:wght@400;600;700' },
  { fontName:'heebo', displayName:'Heebo', cssStack:'"Heebo", system-ui,-apple-system,"Segoe UI",Roboto,Arial,sans-serif', provider:'google', gf:'Heebo:wght@400;600;700' },
  { fontName:'raleway', displayName:'Raleway', cssStack:'"Raleway", "Helvetica Neue", Arial, sans-serif', provider:'google', gf:'Raleway:wght@400;600;700' },
  { fontName:'barlow', displayName:'Barlow', cssStack:'"Barlow", system-ui, -apple-system, "Segoe UI", Roboto, Arial, sans-serif', provider:'google', gf:'Barlow:wght@400;600;700' },
  { fontName:'barlow_condensed', displayName:'Barlow Condensed', cssStack:'"Barlow Condensed", "Barlow", "Helvetica Neue", Arial, sans-serif', provider:'google', gf:'Barlow+Condensed:wght@400;600;700' },
  { fontName:'lexend', displayName:'Lexend', cssStack:'"Lexend", system-ui,-apple-system,"Segoe UI",Roboto,Arial,sans-serif', provider:'google', gf:'Lexend:wght@400;600;700' },
  { fontName:'space_grotesk', displayName:'Space Grotesk', cssStack:'"Space Grotesk", system-ui,-apple-system,"Segoe UI",Roboto,Arial,sans-serif', provider:'google', gf:'Space+Grotesk:wght@400;600;700' },
  { fontName:'sora', displayName:'Sora', cssStack:'"Sora", system-ui,-apple-system,"Segoe UI",Roboto,Arial,sans-serif', provider:'google', gf:'Sora:wght@400;600;700' },
  { fontName:'sen', displayName:'Sen', cssStack:'"Sen", system-ui,-apple-system,"Segoe UI",Roboto,Arial,sans-serif', provider:'google', gf:'Sen:wght@400;600;700' },
  { fontName:'urbanist', displayName:'Urbanist', cssStack:'"Urbanist", system-ui,-apple-system,"Segoe UI",Roboto,Arial,sans-serif', provider:'google', gf:'Urbanist:wght@400;600;700' },
  { fontName:'public_sans', displayName:'Public Sans', cssStack:'"Public Sans", system-ui,-apple-system,"Segoe UI",Roboto,Arial,sans-serif', provider:'google', gf:'Public+Sans:wght@400;600;700' },
  { fontName:'karla', displayName:'Karla', cssStack:'"Karla", system-ui,-apple-system,"Segoe UI",Roboto,Arial,sans-serif', provider:'google', gf:'Karla:wght@400;600;700' },
  { fontName:'cabin', displayName:'Cabin', cssStack:'"Cabin", system-ui,-apple-system,"Segoe UI",Roboto,Arial,sans-serif', provider:'google', gf:'Cabin:wght@400;600;700' },
  { fontName:'atkinson_hyperlegible', displayName:'Atkinson Hyperlegible', cssStack:'"Atkinson Hyperlegible", system-ui,-apple-system,"Segoe UI",Roboto,Arial,sans-serif', provider:'google', gf:'Atkinson+Hyperlegible:wght@400;600;700' },
  { fontName:'pt_sans', displayName:'PT Sans', cssStack:'"PT Sans", system-ui,-apple-system,"Segoe UI",Roboto,Arial,sans-serif', provider:'google', gf:'PT+Sans:wght@400;700' },
  { fontName:'pt_sans_narrow', displayName:'PT Sans Narrow', cssStack:'"PT Sans Narrow", "PT Sans", system-ui, sans-serif', provider:'google', gf:'PT+Sans+Narrow:wght@400;700' },
  { fontName:'hind', displayName:'Hind', cssStack:'"Hind", system-ui,-apple-system,"Segoe UI",Roboto,Arial,sans-serif', provider:'google', gf:'Hind:wght@400;600;700' },
  { fontName:'exo_2', displayName:'Exo 2', cssStack:'"Exo 2", "Exo", system-ui, sans-serif', provider:'google', gf:'Exo+2:wght@400;600;700' },
  { fontName:'rubik', displayName:'Rubik', cssStack:'"Rubik", system-ui,-apple-system,"Segoe UI",Roboto,Arial,sans-serif', provider:'google', gf:'Rubik:wght@400;600;700' },
  { fontName:'asap', displayName:'Asap', cssStack:'"Asap", system-ui,-apple-system,"Segoe UI",Roboto,Arial,sans-serif', provider:'google', gf:'Asap:wght@400;600;700' },
  { fontName:'red_hat_text', displayName:'Red Hat Text', cssStack:'"Red Hat Text", system-ui,-apple-system,"Segoe UI",Roboto,Arial,sans-serif', provider:'google', gf:'Red+Hat+Text:wght@400;600;700' },
  { fontName:'gentium_sans', displayName:'Gentium Plus (Sans alt)', cssStack:'"Gentium Plus", serif', provider:'google', gf:'Gentium+Plus:wght@400;600;700' },
  { fontName:'merriweather', displayName:'Merriweather', cssStack:'"Merriweather", Georgia, serif', provider:'google', gf:'Merriweather:wght@400;700' },
  { fontName:'source_serif_4', displayName:'Source Serif 4', cssStack:'"Source Serif 4", Georgia, serif', provider:'google', gf:'Source+Serif+4:wght@400;600;700' },
  { fontName:'lora', displayName:'Lora', cssStack:'"Lora", Georgia, serif', provider:'google', gf:'Lora:wght@400;600;700' },
  { fontName:'playfair_display', displayName:'Playfair Display', cssStack:'"Playfair Display", Georgia, serif', provider:'google', gf:'Playfair+Display:wght@400;600;700' },
  { fontName:'crimson_pro', displayName:'Crimson Pro', cssStack:'"Crimson Pro", Georgia, serif', provider:'google', gf:'Crimson+Pro:wght@400;600;700' },
  { fontName:'libre_baskerville', displayName:'Libre Baskerville', cssStack:'"Libre Baskerville", Georgia, serif', provider:'google', gf:'Libre+Baskerville:wght@400;700' },
  { fontName:'eb_garamond', displayName:'EB Garamond', cssStack:'"EB Garamond", Georgia, serif', provider:'google', gf:'EB+Garamond:wght@400;600;700' },
  { fontName:'domine', displayName:'Domine', cssStack:'"Domine", Georgia, serif', provider:'google', gf:'Domine:wght@400;700' },
  { fontName:'bitter', displayName:'Bitter', cssStack:'"Bitter", Georgia, serif', provider:'google', gf:'Bitter:wght@400;600;700' },
  { fontName:'spectral', displayName:'Spectral', cssStack:'"Spectral", Georgia, serif', provider:'google', gf:'Spectral:wght@400;600;700' },
  { fontName:'cormorant_garamond', displayName:'Cormorant Garamond', cssStack:'"Cormorant Garamond", Georgia, serif', provider:'google', gf:'Cormorant+Garamond:wght@400;600;700' },
  // Fraunces variable axis simplified to weight-only subset for compatibility
  { fontName:'fraunces', displayName:'Fraunces', cssStack:'"Fraunces", Georgia, serif', provider:'google', gf:'Fraunces:wght@400;600;700' },
  { fontName:'cardo', displayName:'Cardo', cssStack:'"Cardo", Georgia, serif', provider:'google', gf:'Cardo:wght@400;700' },
  { fontName:'zilla_slab', displayName:'Zilla Slab', cssStack:'"Zilla Slab", Georgia, serif', provider:'google', gf:'Zilla+Slab:wght@400;600;700' },
  { fontName:'arvo', displayName:'Arvo', cssStack:'"Arvo", Georgia, serif', provider:'google', gf:'Arvo:wght@400;700' },
  { fontName:'alegreya', displayName:'Alegreya', cssStack:'"Alegreya", Georgia, serif', provider:'google', gf:'Alegreya:wght@400;600;700' },
  { fontName:'vollkorn', displayName:'Vollkorn', cssStack:'"Vollkorn", Georgia, serif', provider:'google', gf:'Vollkorn:wght@400;600;700' },
  { fontName:'gentium_book_plus', displayName:'Gentium Book Plus', cssStack:'"Gentium Book Plus", Georgia, serif', provider:'google', gf:'Gentium+Book+Plus:wght@400;600;700' },
  { fontName:'pt_serif', displayName:'PT Serif', cssStack:'"PT Serif", Georgia, serif', provider:'google', gf:'PT+Serif:wght@400;700' },
  { fontName:'noto_serif', displayName:'Noto Serif', cssStack:'"Noto Serif", Georgia, serif', provider:'google', gf:'Noto+Serif:wght@400;600;700' },
  { fontName:'newsreader', displayName:'Newsreader', cssStack:'"Newsreader", Georgia, serif', provider:'google', gf:'Newsreader:wght@400;600;700' },
  { fontName:'literata', displayName:'Literata', cssStack:'"Literata", Georgia, serif', provider:'google', gf:'Literata:wght@400;600;700' },
  { fontName:'roboto_slab', displayName:'Roboto Slab', cssStack:'"Roboto Slab", Roboto, serif', provider:'google', gf:'Roboto+Slab:wght@400;600;700' },
  { fontName:'archivo', displayName:'Archivo', cssStack:'"Archivo", system-ui, sans-serif', provider:'google', gf:'Archivo:wght@400;600;700' },
  { fontName:'archivo_narrow', displayName:'Archivo Narrow', cssStack:'"Archivo Narrow", "Archivo", system-ui, sans-serif', provider:'google', gf:'Archivo+Narrow:wght@400;600;700' },
  { fontName:'josefin_slab', displayName:'Josefin Slab', cssStack:'"Josefin Slab", Georgia, serif', provider:'google', gf:'Josefin+Slab:wght@400;600;700' },
  { fontName:'besley', displayName:'Besley', cssStack:'"Besley", Georgia, serif', provider:'google', gf:'Besley:wght@400;600;700' },
  { fontName:'jetbrains_mono', displayName:'JetBrains Mono', cssStack:'"JetBrains Mono", ui-monospace, SFMono-Regular, Menlo, Consolas, "Liberation Mono", monospace', provider:'google', gf:'JetBrains+Mono:wght@400;600;700' },
  { fontName:'fira_code', displayName:'Fira Code', cssStack:'"Fira Code", ui-monospace, SFMono-Regular, Menlo, Consolas, "Liberation Mono", monospace', provider:'google', gf:'Fira+Code:wght@400;500;600' },
  { fontName:'cascadia_code', displayName:'Cascadia Code (local)', cssStack:'"Cascadia Code", "Cascadia Mono", ui-monospace, SFMono-Regular, Menlo, Consolas, monospace', provider:'system' },
  { fontName:'source_code_pro', displayName:'Source Code Pro', cssStack:'"Source Code Pro", ui-monospace, SFMono-Regular, Menlo, Consolas, monospace', provider:'google', gf:'Source+Code+Pro:wght@400;600;700' },
  { fontName:'ibm_plex_mono', displayName:'IBM Plex Mono', cssStack:'"IBM Plex Mono", ui-monospace, SFMono-Regular, Menlo, Consolas, monospace', provider:'google', gf:'IBM+Plex+Mono:wght@400;600;700' },
  { fontName:'inconsolata', displayName:'Inconsolata', cssStack:'"Inconsolata", ui-monospace, SFMono-Regular, Menlo, Consolas, monospace', provider:'google', gf:'Inconsolata:wght@400;600;700' },
  { fontName:'hack', displayName:'Hack', cssStack:'"Hack", ui-monospace, SFMono-Regular, Menlo, Consolas, monospace', provider:'other', gf:'' },
  { fontName:'pt_mono', displayName:'PT Mono', cssStack:'"PT Mono", ui-monospace, SFMono-Regular, Menlo, Consolas, monospace', provider:'google', gf:'PT+Mono' },
  { fontName:'recursive', displayName:'Recursive', cssStack:'"Recursive", ui-monospace, SFMono-Regular, Menlo, Consolas, monospace', provider:'google', gf:'Recursive:wght@400;600;700' },
  { fontName:'victor_mono', displayName:'Victor Mono', cssStack:'"Victor Mono", ui-monospace, SFMono-Regular, Menlo, Consolas, monospace', provider:'google', gf:'Victor+Mono:wght@400;600;700' },
  { fontName:'iosevka', displayName:'Iosevka (local)', cssStack:'"Iosevka", ui-monospace, SFMono-Regular, Menlo, Consolas, monospace', provider:'system' },
  { fontName:'jetbrains_serif', displayName:'JetBrains Serif', cssStack:'"JetBrains Serif", Georgia, serif', provider:'other' },
  { fontName:'bebas_neue', displayName:'Bebas Neue', cssStack:'"Bebas Neue", "Impact", "Arial Narrow", sans-serif', provider:'google', gf:'Bebas+Neue' },
  { fontName:'bangers', displayName:'Bangers', cssStack:'"Bangers", Impact, "Arial Black", sans-serif', provider:'google', gf:'Bangers' },
  { fontName:'oswald', displayName:'Oswald', cssStack:'"Oswald", "Helvetica Neue", Arial, sans-serif', provider:'google', gf:'Oswald:wght@400;500;600;700' },
  { fontName:'anton', displayName:'Anton', cssStack:'"Anton", "Arial Black", Impact, sans-serif', provider:'google', gf:'Anton' },
  { fontName:'abril_fatface', displayName:'Abril Fatface', cssStack:'"Abril Fatface", Georgia, serif', provider:'google', gf:'Abril+Fatface' },
  { fontName:'alfa_slab_one', displayName:'Alfa Slab One', cssStack:'"Alfa Slab One", Georgia, serif', provider:'google', gf:'Alfa+Slab+One' },
  { fontName:'bungee', displayName:'Bungee', cssStack:'"Bungee", "Arial Black", Impact, sans-serif', provider:'google', gf:'Bungee' },
  { fontName:'righteous', displayName:'Righteous', cssStack:'"Righteous", "Trebuchet MS", sans-serif', provider:'google', gf:'Righteous' },
  { fontName:'fredoka', displayName:'Fredoka', cssStack:'"Fredoka", "Poppins", "Helvetica Neue", Arial, sans-serif', provider:'google', gf:'Fredoka:wght@400;500;600;700' },
  { fontName:'kanit', displayName:'Kanit', cssStack:'"Kanit", system-ui, -apple-system, "Segoe UI", Roboto, Arial, sans-serif', provider:'google', gf:'Kanit:wght@400;500;600;700' },
  { fontName:'exo', displayName:'Exo', cssStack:'"Exo", system-ui, sans-serif', provider:'google', gf:'Exo:wght@400;600;700' },
  { fontName:'orbitron', displayName:'Orbitron', cssStack:'"Orbitron", system-ui, sans-serif', provider:'google', gf:'Orbitron:wght@400;600;700' },
  { fontName:'rajdhani', displayName:'Rajdhani', cssStack:'"Rajdhani", system-ui, sans-serif', provider:'google', gf:'Rajdhani:wght@400;600;700' },
  { fontName:'staatliches', displayName:'Staatliches', cssStack:'"Staatliches", "Impact", "Arial Narrow", sans-serif', provider:'google', gf:'Staatliches' },
  { fontName:'squada_one', displayName:'Squada One', cssStack:'"Squada One", "Impact", "Arial Narrow", sans-serif', provider:'google', gf:'Squada+One' },
  { fontName:'rubik_mono_one', displayName:'Rubik Mono One', cssStack:'"Rubik Mono One", "Rubik", system-ui, sans-serif', provider:'google', gf:'Rubik+Mono+One' },
  { fontName:'fjalla_one', displayName:'Fjalla One', cssStack:'"Fjalla One", "Impact", "Arial Narrow", sans-serif', provider:'google', gf:'Fjalla+One' },
  { fontName:'chivo', displayName:'Chivo', cssStack:'"Chivo", system-ui, sans-serif', provider:'google', gf:'Chivo:wght@400;600;700' },
  { fontName:'league_gothic', displayName:'League Gothic', cssStack:'"League Gothic", "Arial Narrow", sans-serif', provider:'other' },
  { fontName:'archivo_black', displayName:'Archivo Black', cssStack:'"Archivo Black", "Archivo", system-ui, sans-serif', provider:'google', gf:'Archivo+Black' },
  { fontName:'caveat', displayName:'Caveat', cssStack:'"Caveat", "Comic Sans MS", cursive', provider:'google', gf:'Caveat:wght@400;600;700' },
  { fontName:'indie_flower', displayName:'Indie Flower', cssStack:'"Indie Flower", "Comic Sans MS", cursive', provider:'google', gf:'Indie+Flower' },
  { fontName:'kalam', displayName:'Kalam', cssStack:'"Kalam", "Comic Sans MS", cursive', provider:'google', gf:'Kalam:wght@400;600;700' },
  { fontName:'amatic_sc', displayName:'Amatic SC', cssStack:'"Amatic SC", cursive', provider:'google', gf:'Amatic+SC:wght@400;700' },
  { fontName:'patrick_hand', displayName:'Patrick Hand', cssStack:'"Patrick Hand", cursive', provider:'google', gf:'Patrick+Hand' },
  { fontName:'shadows_into_light', displayName:'Shadows Into Light', cssStack:'"Shadows Into Light", cursive', provider:'google', gf:'Shadows+Into+Light' },
  { fontName:'satisfy', displayName:'Satisfy', cssStack:'"Satisfy", cursive', provider:'google', gf:'Satisfy' },
  { fontName:'pacifico', displayName:'Pacifico', cssStack:'"Pacifico", cursive', provider:'google', gf:'Pacifico' },
  { fontName:'dancing_script', displayName:'Dancing Script', cssStack:'"Dancing Script", cursive', provider:'google', gf:'Dancing+Script:wght@400;600;700' },
  { fontName:'great_vibes', displayName:'Great Vibes', cssStack:'"Great Vibes", cursive', provider:'google', gf:'Great+Vibes' },
  { fontName:'yellowtail', displayName:'Yellowtail', cssStack:'"Yellowtail", cursive', provider:'google', gf:'Yellowtail' },
  { fontName:'nanum_pen_script', displayName:'Nanum Pen Script', cssStack:'"Nanum Pen Script", cursive', provider:'google', gf:'Nanum+Pen+Script' },
  { fontName:'gloria_hallelujah', displayName:'Gloria Hallelujah', cssStack:'"Gloria Hallelujah", cursive', provider:'google', gf:'Gloria+Hallelujah' },
  { fontName:'nunito_sans', displayName:'Nunito Sans', cssStack:'"Nunito Sans", "Nunito", system-ui, sans-serif', provider:'google', gf:'Nunito+Sans:wght@400;600;700' },
  { fontName:'quicksand', displayName:'Quicksand', cssStack:'"Quicksand", system-ui, sans-serif', provider:'google', gf:'Quicksand:wght@400;600;700' },
  { fontName:'baloo_2', displayName:'Baloo 2', cssStack:'"Baloo 2", cursive', provider:'google', gf:'Baloo+2:wght@400;600;700' },
  { fontName:'varela_round', displayName:'Varela Round', cssStack:'"Varela Round", system-ui, sans-serif', provider:'google', gf:'Varela+Round' },
  { fontName:'m_plus_rounded_1c', displayName:'M PLUS Rounded 1c', cssStack:'"M PLUS Rounded 1c", system-ui, sans-serif', provider:'google', gf:'M+PLUS+Rounded+1c:wght@400;600;700' },
  { fontName:'comfortaa', displayName:'Comfortaa', cssStack:'"Comfortaa", system-ui, sans-serif', provider:'google', gf:'Comfortaa:wght@400;600;700' },
  { fontName:'roboto_condensed', displayName:'Roboto Condensed', cssStack:'"Roboto Condensed", Roboto, system-ui, sans-serif', provider:'google', gf:'Roboto+Condensed:wght@400;500;700' },
  { fontName:'barlow_semi_condensed', displayName:'Barlow Semi Condensed', cssStack:'"Barlow Semi Condensed", "Barlow", system-ui, sans-serif', provider:'google', gf:'Barlow+Semi+Condensed:wght@400;600;700' },
  { fontName:'open_sans_condensed', displayName:'Open Sans Condensed', cssStack:'"Open Sans Condensed", "Open Sans", system-ui, sans-serif', provider:'google', gf:'Open+Sans+Condensed:wght@300;700' },
  { fontName:'saira_condensed', displayName:'Saira Condensed', cssStack:'"Saira Condensed", system-ui, sans-serif', provider:'google', gf:'Saira+Condensed:wght@400;600;700' },
  { fontName:'inter_tight', displayName:'Inter Tight', cssStack:'"Inter Tight", "Inter", system-ui, sans-serif', provider:'google', gf:'Inter+Tight:wght@400;600;700' },
  // System fallback option
  { fontName:'system', displayName:'System Default', cssStack:'system-ui, -apple-system, "Segoe UI", Roboto, Arial, sans-serif', provider:'system' }
];

export function getFontMeta(id) {
  return FONT_CATALOG.find(f => f.fontName === id) || FONT_CATALOG.find(f=>f.fontName==='system');
}

// NOTE: To add proprietary or custom fonts later: supply WOFF2 files + @font-face, then push an entry into FONT_CATALOG at runtime.
// Keep licensing compliance in mind; do not bundle fonts without redistribution rights.
